### PR TITLE
Add closePath() in two places

### PR DESCRIPTION
**Pull request by tobireif**
One results in a fixed shape in the demo, one is for consistency :)

### CODE REVIEW

**Comment by tobireif** [comment]
Can this get merged? (no hurry, just asking 😀)

**Comment by ivanpopelyshev** [comment]
IT was merged: https://github.com/pixijs/examples/pull/70

**Comment by ivanpopelyshev** [comment]
Oh right that's another one. but yuou didnt make a PR in original repo , you made it here :)))))))

**Comment by tobireif** [comment]
Oops! The one related PR went well, but this one I botched. Sorry.

Here's the new PR: https://github.com/pixijs/examples/pull/71

**Pull request closed without merging**
